import { ReactElement, useCallback, CSSProperties } from "react";
import { BarChart } from "./components/BarChart";
import { buildSeries } from "./utils/seriesBuilder";
import "./ui/EChartsLineChart.css";

// Props are generated by the build tool from EChartsBarChart.xml.
// Typed inline here to avoid a separate typings file for this prototype.
interface EChartsBarChartContainerProps {
    name: string;
    class: string;
    style?: CSSProperties;
    tabIndex?: number;
    series: any[];
    enableAdvancedOptions: boolean;
    horizontal: boolean;
    stack: boolean;
    barWidth: string;
    categoryAxisLabel?: { value?: string };
    categoryDateFormat: string;
    backgroundColor: string;
    valueAxisLabel?: { value?: string };
    showLegend: boolean;
    legendPosition: "top" | "bottom" | "left" | "right";
    gridLines: "none" | "horizontal" | "vertical" | "both";
    enableTimeline: boolean;
    timelineDateFormat: string;
    timelineAutoPlay: boolean;
    timelineLoop: boolean;
    timelinePlayInterval: number;
    timelineRewind: boolean;
    widthUnit: "percentage" | "pixels";
    width: number;
    heightUnit: "percentageOfWidth" | "pixels" | "percentageOfParent";
    height: number;
    customLayout: string;
    customConfigurations: string;
}

export function EChartsBarChart(props: EChartsBarChartContainerProps): ReactElement {
    const {
        series: seriesProps,
        horizontal,
        stack,
        barWidth,
        categoryAxisLabel,
        categoryDateFormat,
        backgroundColor,
        valueAxisLabel,
        showLegend,
        legendPosition,
        gridLines,
        enableTimeline,
        timelineDateFormat,
        timelineAutoPlay,
        timelineLoop,
        timelinePlayInterval,
        timelineRewind,
        widthUnit,
        width,
        heightUnit,
        height,
        customLayout,
        customConfigurations,
        class: className,
        style
    } = props;

    // Re-use the same seriesBuilder: staticLineColor/dynamicLineColor holds bar color
    // because the bar XML maps staticBarColor → same position in the builder
    const builtSeries = buildSeries(
        seriesProps.map((s: any) => ({
            ...s,
            // Map bar-specific color props to what seriesBuilder expects
            staticLineColor: s.staticBarColor,
            dynamicLineColor: s.dynamicBarColor,
            // Bar has no interpolation/lineStyle; provide safe defaults
            interpolation: "linear",
            lineStyle: "line"
        }))
    );

    const onDataPointClick = useCallback(
        (seriesIndex: number, dataIndex: number) => {
            const built = builtSeries[seriesIndex];
            if (!built) return;
            const clickedItem = built.onClickItems[dataIndex];
            if (!clickedItem) return;
            const line = seriesProps[seriesIndex];
            if (!line) return;
            if (line.dataSet === "static" && line.staticOnClickAction) {
                const action = line.staticOnClickAction.get(clickedItem);
                if (action.canExecute) action.execute();
            } else if (line.dataSet === "dynamic" && line.dynamicOnClickAction) {
                const action = line.dynamicOnClickAction.get(clickedItem);
                if (action.canExecute) action.execute();
            }
        },
        [builtSeries, seriesProps]
    );

    const containerStyle = buildContainerStyle(widthUnit, width, heightUnit, height, style);

    return (
        <div className={`widget-echarts ${className}`} style={containerStyle}>
            <BarChart
                series={builtSeries}
                categoryAxisLabel={categoryAxisLabel?.value ?? ""}
                xAxisDateFormat={categoryDateFormat || undefined}
                backgroundColor={backgroundColor || undefined}
                valueAxisLabel={valueAxisLabel?.value ?? ""}
                showLegend={showLegend}
                legendPosition={legendPosition}
                gridLines={gridLines}
                horizontal={horizontal}
                stack={stack}
                barWidth={barWidth || undefined}
                timelineConfig={enableTimeline ? {
                    autoPlay: timelineAutoPlay,
                    loop: timelineLoop,
                    playInterval: timelinePlayInterval,
                    rewind: timelineRewind,
                    dateFormat: timelineDateFormat || undefined
                } : undefined}
                customOption={customLayout || undefined}
                customInitOptions={customConfigurations || undefined}
                onDataPointClick={onDataPointClick}
            />
        </div>
    );
}

function buildContainerStyle(
    widthUnit: "percentage" | "pixels",
    width: number,
    heightUnit: "percentageOfWidth" | "pixels" | "percentageOfParent",
    height: number,
    extraStyle?: CSSProperties
): CSSProperties {
    const style: CSSProperties = { ...extraStyle };
    style.width = widthUnit === "pixels" ? `${width}px` : `${width}%`;
    if (heightUnit === "pixels") {
        style.height = `${height}px`;
    } else if (heightUnit === "percentageOfParent") {
        style.height = `${height}%`;
    } else {
        style.aspectRatio = `100 / ${height}`;
        style.height = "auto";
    }
    return style;
}
